import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Clock3, House, MessageCircle, Package, ShieldCheck, Truck, Zap } from 'lucide-react';
import QuoteForm from '@/components/QuoteForm';

const wa = 'https://wa.me/27788868252';
const services = [
  { icon: House, title: 'Furniture moves', text: 'Beds, couches, appliances and more, moved with care across Cape Town.' },
  { icon: Package, title: 'Junk & rubble removal', text: 'Clear garages, garden waste, old furniture and building rubble in one trip.' },
  { icon: Truck, title: 'Business deliveries', text: 'Reliable delivery support for shops, estate agents and small businesses.' }
];
const testimonials = [
  ['“Moved my 2-bed in Mitchells Plain super quick. The driver was careful and on time.”', 'Aisha M.', 'Mitchells Plain'],
  ['“The quote was clear, and they took away all the garden rubble without any fuss.”', 'Jason P.', 'Strandfontein'],
  ['“JRMS helped us deliver stock to three customers in one afternoon. Great service.”', 'Nadia S.', 'Muizenberg']
];

export default function Home() {
  return <main>
    <section className="overflow-hidden bg-[#f3f7fd]"><div className="container grid min-h-[600px] items-center gap-12 py-20 lg:grid-cols-[1.03fr_.97fr] lg:py-24">
      <div className="relative z-10"><div className="eyebrow mb-5 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-lime-500" /> Cape Town's local logistics crew</div><h1 className="max-w-2xl text-5xl font-black leading-[1.03] tracking-[-.055em] text-ink sm:text-6xl">Reliable moves & junk removal <span className="text-brand">from R399.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Strandfontein based. Bakkies and trucks on demand. Same-day available. Book in two minutes and get a fair, fixed quote.</p><div className="mt-8 flex flex-wrap gap-3"><a href={wa} target="_blank" rel="noreferrer" className="btn btn-primary">Book on WhatsApp <ArrowRight size={17} /></a><a href="#quote" className="btn btn-outline">Get instant quote <ArrowDown size={17} /></a></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-slate-600"><span className="flex items-center gap-2"><Check size={17} className="text-brand" /> 500+ jobs</span><span className="flex items-center gap-2"><Clock3 size={17} className="text-brand" /> Same-day</span><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-brand" /> Insured drivers</span></div></div>
      <div className="relative mx-auto w-full max-w-[470px] lg:mr-0"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full border-[28px] border-white/70" /><div className="relative overflow-hidden rounded-2xl bg-brand p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/20 pb-5 text-white"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-200">On the road today</p><p className="mt-1 text-2xl font-black">Cape Town, ready.</p></div><div className="rounded-xl bg-white/15 p-3"><Truck size={27} /></div></div><div className="relative mt-5 rounded-xl bg-white p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Your job</p><p className="mt-1 font-extrabold text-ink">2-bedroom move</p></div><span className="rounded-full bg-lime-100 px-3 py-1 text-xs font-black text-green-800">Available</span></div><div className="my-5 flex items-center gap-3"><div className="flex flex-col items-center gap-1"><span className="h-3 w-3 rounded-full border-4 border-blue-100 bg-brand" /><span className="h-9 border-l border-dashed border-slate-300" /><span className="h-3 w-3 rounded-full bg-lime-500" /></div><div className="grid gap-5 text-sm"><div><p className="font-bold text-ink">Mitchells Plain</p><p className="text-xs text-slate-500">Collection, 09:30</p></div><div><p className="font-bold text-ink">Muizenberg</p><p className="text-xs text-slate-500">Delivery, today</p></div></div></div><div className="flex items-end justify-between border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-500">Estimated from</p><p className="text-2xl font-black text-brand">R599</p></div><div className="flex -space-x-2"><span className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-blue-100 text-xs font-bold text-brand">SJ</span><span className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white bg-lime-100 text-xs font-bold text-green-800">TK</span></div></div></div><div className="mt-5 flex items-center gap-3 text-sm font-semibold text-blue-100"><Zap size={17} fill="currentColor" /> Live driver network across the peninsula</div></div></div>
    </div></section>

    <section id="services" className="section-pad"><div className="container"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow mb-3">One platform. Every load.</p><h2 className="text-4xl font-black tracking-[-.045em] text-ink">A capable crew for the jobs<br className="hidden sm:block" /> Cape Town throws at you.</h2></div><p className="max-w-sm text-sm leading-7 text-slate-500">From a single couch to a full home move, we match your job with the right vehicle and driver.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{services.map(({ icon: Icon, title, text }, index) => <div key={title} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><div className={`mb-7 flex h-12 w-12 items-center justify-center rounded-xl ${index === 1 ? 'bg-lime-100 text-green-800' : 'bg-sky text-brand'}`}><Icon size={24} /></div><h3 className="text-xl font-extrabold text-ink">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{text}</p><a href="#quote" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand">Get a quote <ArrowRight size={16} /></a></div>)}</div></div></section>

    <section id="how-it-works" className="bg-mist section-pad"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-3">Simple by design</p><h2 className="text-4xl font-black tracking-[-.045em] text-ink">Move more.<br />Stress less.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-500">No call centre maze. No mystery pricing. Just send us what you need moved and we will take it from there.</p><a href={wa} target="_blank" rel="noreferrer" className="btn btn-primary mt-7">Start on WhatsApp <MessageCircle size={17} /></a></div><div className="grid gap-4">{[['01','Send photos on WhatsApp','Show us the items, access and both areas. Photos help us quote accurately.'],['02','Get a fixed price','We confirm your price and a suitable driver before the job starts.'],['03','Driver arrives, job done','Your driver handles the move and uploads proof when it is complete.']].map(([number, title, text]) => <div key={number} className="flex gap-5 rounded-xl border border-slate-200 bg-white p-6"><span className="text-sm font-black text-brand">{number}</span><div><h3 className="font-extrabold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div></div>)}</div></div></section>

    <section id="pricing" className="section-pad"><div className="container"><div className="text-center"><p className="eyebrow mb-3">Clear starting points</p><h2 className="text-4xl font-black tracking-[-.045em] text-ink">Fair prices, no surprises.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-slate-500">Every job is different. These starting prices help you plan, and your final quote is confirmed before we arrive.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3">{[['R399','Local essentials','Small items or a short local trip'],['R599','2-bedroom move','A popular move with a bakkie'],['Custom','Big jobs','Full homes, rubble or business loads']].map(([price, title, text], i) => <div key={title} className={`rounded-2xl border p-7 ${i === 1 ? 'border-brand bg-brand text-white shadow-soft' : 'border-slate-200 bg-white'}`}><p className={`text-sm font-bold ${i === 1 ? 'text-blue-200' : 'text-slate-400'}`}>{title}</p><p className="mt-4 text-4xl font-black">{price}{price !== 'Custom' && <span className={`text-base font-bold ${i === 1 ? 'text-blue-200' : 'text-slate-400'}`}>+</span>}</p><p className={`mt-3 text-sm leading-6 ${i === 1 ? 'text-blue-100' : 'text-slate-500'}`}>{text}</p><div className={`mt-7 border-t pt-5 text-xs font-bold ${i === 1 ? 'border-white/20 text-blue-100' : 'border-slate-100 text-slate-500'}`}>85% goes to your driver · 15% platform fee</div></div>)}</div></div></section>

    <section id="quote" className="bg-[#edf4ff] section-pad"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow mb-3">Tell us about the job</p><h2 className="text-4xl font-black tracking-[-.045em] text-ink">Get your quote<br />in two minutes.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-slate-600">Fill in the basics and WhatsApp will open with everything ready to send. Add photos there for your most accurate price.</p><div className="mt-8 grid gap-3 text-sm font-bold text-slate-600"><span className="flex items-center gap-3"><ShieldCheck size={18} className="text-brand" /> No obligation</span><span className="flex items-center gap-3"><Zap size={18} className="text-brand" /> Same-day options</span></div></div><div className="rounded-2xl bg-white p-6 shadow-soft sm:p-8"><QuoteForm /></div></div></section>

    <section className="section-pad"><div className="container"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow mb-3">Good people, good moves</p><h2 className="text-4xl font-black tracking-[-.045em] text-ink">What Cape Town says.</h2></div><p className="text-sm text-slate-500">Real work. Local recommendations.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.map(([quote, name, area]) => <div key={name} className="rounded-2xl border border-slate-200 p-6"><div className="mb-6 flex gap-1 text-lg text-brand">★★★★★</div><p className="min-h-20 text-sm font-semibold leading-7 text-ink">{quote}</p><div className="mt-6 border-t border-slate-100 pt-4"><p className="text-sm font-extrabold">{name}</p><p className="mt-1 text-xs text-slate-500">{area}</p></div></div>)}</div></div></section>

    <section id="contact" className="bg-brand py-16 text-white"><div className="container flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-blue-200">Ready when you are</p><h2 className="text-3xl font-black tracking-[-.03em]">Let's get your load moving.</h2><p className="mt-3 text-sm text-blue-100">Serving Strandfontein and all Cape Town, seven days a week.</p></div><a href={wa} target="_blank" rel="noreferrer" className="btn btn-light">WhatsApp JRMS <ArrowUpRight size={17} /></a></div></section>
  </main>;
}
