'use client';

import { useEffect, useState } from 'react';
import { BarChart3, CheckCircle2, Download, LogOut, X } from 'lucide-react';
import { supabase } from '../lib/supabase';

const feeRate = 0.2;
const rangeLabels = { thisWeek: 'This Week', lastWeek: 'Last Week', thisMonth: 'This Month' };

function dateOnly(date) { return date.toISOString().slice(0, 10); }
function startOfWeek(date) { const result = new Date(date); const day = result.getDay(); result.setDate(result.getDate() - (day === 0 ? 6 : day - 1)); result.setHours(0, 0, 0, 0); return result; }
function getRange(key) {
  const today = new Date();
  if (key === 'thisMonth') return { start: new Date(today.getFullYear(), today.getMonth(), 1), end: new Date(today.getFullYear(), today.getMonth() + 1, 0, 23, 59, 59, 999) };
  const thisMonday = startOfWeek(today);
  if (key === 'lastWeek') return { start: new Date(thisMonday.getTime() - 7 * 86400000), end: new Date(thisMonday.getTime() - 1) };
  return { start: thisMonday, end: new Date(thisMonday.getTime() + 6 * 86400000 + 86399999) };
}
function money(value) { return `R${Number(value || 0).toLocaleString('en-ZA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default function AdminDashboard() {
  const [loggedIn, setLoggedIn] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState('');
  if (!loggedIn) return <main className="bg-mist"><div className="container flex min-h-[620px] items-center justify-center py-16"><form onSubmit={event => { event.preventDefault(); if (email === 'solomonslogan7@gmail.com' && password === 'Global86!!!') { setLoggedIn(true); setLoginError(''); } else setLoginError('Incorrect admin email or password.'); }} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-soft"><div className="mb-8"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl bg-brand text-white"><BarChart3 /></div><p className="eyebrow mb-2">JRMS operations</p><h1 className="text-3xl font-black tracking-[-.04em]">Admin login.</h1></div><label className="mb-1.5 block text-xs font-bold text-slate-600">Email</label><input required type="email" className="field mb-4" value={email} onChange={event => setEmail(event.target.value)} /><label className="mb-1.5 block text-xs font-bold text-slate-600">Password</label><input required type="password" className="field" value={password} onChange={event => setPassword(event.target.value)} />{loginError && <p className="mt-3 text-sm font-semibold text-red-600">{loginError}</p>}<button className="btn btn-primary mt-6 w-full">Sign in</button></form></div></main>;
  return <AdminWorkspace onLogout={() => setLoggedIn(false)} />;
}

function AdminWorkspace({ onLogout }) {
  const [tab, setTab] = useState('applications'); const [applications, setApplications] = useState([]); const [drivers, setDrivers] = useState([]); const [bookings, setBookings] = useState([]); const [range, setRange] = useState('thisWeek'); const [payoutRows, setPayoutRows] = useState([]); const [paidIds, setPaidIds] = useState(new Set()); const [error, setError] = useState(''); const [loadingPayouts, setLoadingPayouts] = useState(false);
  const load = async () => { const [{ data: driverData, error: driverError }, { data: bookingData, error: bookingError }] = await Promise.all([supabase.from('drivers').select('*').order('created_at', { ascending: false }), supabase.from('bookings').select('*').order('created_at', { ascending: false })]); if (driverError || bookingError) { setError(driverError?.message || bookingError?.message); return; } setDrivers(driverData || []); setApplications(driverData || []); setBookings(bookingData || []); };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (tab === 'payouts') loadPayouts(); }, [tab, range]);
  const approve = async id => { const { error: updateError } = await supabase.from('drivers').update({ status: 'approved', approved_at: new Date().toISOString() }).eq('id', id); if (updateError) setError(updateError.message); else load(); };
  const reject = async id => { const { error: updateError } = await supabase.from('drivers').update({ status: 'rejected', approved_at: null }).eq('id', id); if (updateError) setError(updateError.message); else load(); };
  const assign = async (bookingId, driverId) => { const { error: updateError } = await supabase.from('bookings').update({ driver_id: driverId || null, status: driverId ? 'assigned' : 'pending' }).eq('id', bookingId); if (updateError) setError(updateError.message); else load(); };
  const loadPayouts = async () => { setLoadingPayouts(true); setError(''); const activeDrivers = await supabase.from('drivers').select('*').eq('status', 'active').order('full_name'); const selected = getRange(range); const completed = await supabase.from('bookings').select('driver_id, fare_amount, price, booking_date, created_at').eq('status', 'completed').gte('booking_date', selected.start.toISOString()).lte('booking_date', selected.end.toISOString()); if (activeDrivers.error || completed.error) { setError(activeDrivers.error?.message || completed.error?.message); setLoadingPayouts(false); return; } const payouts = await supabase.from('payouts').select('driver_id, week_start, week_end, status').eq('status', 'paid').eq('week_start', dateOnly(selected.start)).eq('week_end', dateOnly(selected.end)); if (payouts.error) { setError(payouts.error.message); setLoadingPayouts(false); return; } const totals = new Map(); (completed.data || []).forEach(booking => { if (!booking.driver_id) return; const fare = Number(booking.fare_amount ?? booking.price ?? 0); const current = totals.get(booking.driver_id) || { trips: 0, gross: 0 }; totals.set(booking.driver_id, { trips: current.trips + 1, gross: current.gross + fare }); }); setPaidIds(new Set((payouts.data || []).map(payout => payout.driver_id))); setPayoutRows((activeDrivers.data || []).map(driver => { const total = totals.get(driver.id) || { trips: 0, gross: 0 }; return { driver, trips: total.trips, gross: total.gross, platformFee: total.gross * feeRate, driverPay: total.gross * (1 - feeRate) }; })); setLoadingPayouts(false); };
  const markPaid = async row => { const selected = getRange(range); const { error: insertError } = await supabase.from('payouts').insert({ driver_id: row.driver.id, week_start: dateOnly(selected.start), week_end: dateOnly(selected.end), gross_fare: row.gross, platform_fee: row.platformFee, driver_pay: row.driverPay, status: 'paid', paid_at: new Date().toISOString() }); if (insertError) setError(insertError.code === '23505' ? 'This driver has already been paid for the selected period.' : insertError.message); else { setPaidIds(current => new Set([...current, row.driver.id])); setPayoutRows(current => current.filter(item => item.driver.id !== row.driver.id)); } };
  const exportCsv = () => { const headings = ['Driver Name', 'Phone', 'Car Plate', 'Trips Week', 'Gross Fare', 'Your Profit (20%)', 'To Pay Driver (80%)']; const rows = payoutRows.filter(row => !paidIds.has(row.driver.id)).map(row => [row.driver.full_name || row.driver.name || '', row.driver.phone || '', row.driver.car_plate || '', row.trips, row.gross.toFixed(2), row.platformFee.toFixed(2), row.driverPay.toFixed(2)]); const csv = [headings, ...rows].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = `jrms-driver-payouts-${range}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <main className="bg-mist"><div className="container py-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">JRMS operations</p><h1 className="text-4xl font-black tracking-[-.045em]">Admin dashboard</h1><p className="mt-2 text-sm text-slate-500">Manage applications, bookings and driver payouts.</p></div><button onClick={onLogout} className="flex items-center gap-2 self-start text-sm font-bold text-slate-500"><LogOut size={16} /> Log out</button></div>{error && <p className="mt-5 text-sm font-semibold text-red-600">{error}</p>}
    <div className="mt-8 flex flex-wrap gap-2 border-b border-slate-200"><Tab active={tab === 'applications'} onClick={() => setTab('applications')}>Applications <span>{applications.length}</span></Tab><Tab active={tab === 'bookings'} onClick={() => setTab('bookings')}>Bookings <span>{bookings.length}</span></Tab><Tab active={tab === 'payouts'} onClick={() => setTab('payouts')}>Driver Payouts</Tab></div>
    {tab === 'applications' && <Applications applications={applications} approve={approve} reject={reject} />}
    {tab === 'bookings' && <Bookings bookings={bookings} drivers={drivers} assign={assign} />}
    {tab === 'payouts' && <Payouts range={range} setRange={setRange} rows={payoutRows} paidIds={paidIds} markPaid={markPaid} exportCsv={exportCsv} loading={loadingPayouts} />}
  </div></main>;
}

function Tab({ active, onClick, children }) { return <button onClick={onClick} className={`border-b-2 px-3 py-3 text-sm font-bold ${active ? 'border-brand text-brand' : 'border-transparent text-slate-500'}`}>{children}</button>; }
function Applications({ applications, approve, reject }) { const [statusTab, setStatusTab] = useState('pending'); const tabs = [['pending', 'Pending'], ['approved', 'Approved'], ['rejected', 'Rejected']]; const visibleApplications = applications.filter(driver => driver.status === statusTab || (statusTab === 'approved' && driver.status === 'active')); return <section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Driver applications</h2><p className="mt-1 text-xs text-slate-500">Review applications and manage driver approval.</p></div><span className="rounded-full bg-sky px-3 py-1 text-xs font-bold text-brand">{visibleApplications.length} {statusTab}</span></div><div className="mt-6 flex flex-wrap gap-2 border-b border-slate-200">{tabs.map(([value, label]) => <Tab key={value} active={statusTab === value} onClick={() => setStatusTab(value)}>{label} <span>{applications.filter(driver => driver.status === value || (value === 'approved' && driver.status === 'active')).length}</span></Tab>)}</div>{visibleApplications.length === 0 ? <p className="mt-6 rounded-xl border border-dashed border-slate-200 px-5 py-10 text-center text-sm text-slate-500">No {statusTab} applications.</p> : <div className="mt-5 divide-y divide-slate-100">{visibleApplications.map(driver => <div key={driver.id} className="flex flex-col justify-between gap-4 py-5 lg:flex-row lg:items-center"><div><p className="font-bold">{driver.full_name || driver.name}</p><p className="mt-1 text-sm text-slate-500">{driver.phone}</p>{statusTab === 'approved' && <p className="mt-1 text-xs text-slate-400">Approved {driver.approved_at ? new Date(driver.approved_at).toLocaleString() : 'date not recorded'}</p>}</div>{statusTab === 'pending' && <div className="flex gap-2"><button onClick={() => approve(driver.id)} className="btn bg-green-600 px-4 py-2 text-sm text-white"><CheckCircle2 size={16} /> Approve</button><button onClick={() => reject(driver.id)} className="btn btn-outline px-4 py-2 text-sm"><X size={16} /> Reject</button></div>}</div>)}</div>}</section>; }
function Bookings({ bookings, drivers, assign }) { return <section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Bookings</h2>{bookings.length === 0 ? <p className="mt-6 text-sm text-slate-500">No bookings yet.</p> : <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase text-slate-400"><th className="pb-3">Route</th><th className="pb-3">Service</th><th className="pb-3">Status</th><th className="pb-3">Driver</th></tr></thead><tbody>{bookings.map(booking => <tr key={booking.id} className="border-b border-slate-50"><td className="py-4 font-bold">{booking.from_area}{booking.to_area ? ` to ${booking.to_area}` : ''}</td><td className="py-4">{booking.service_type}</td><td className="py-4">{booking.status}</td><td className="py-4"><select className="field min-w-[180px]" value={booking.driver_id || ''} onChange={event => assign(booking.id, event.target.value)}><option value="">Unassigned</option>{drivers.filter(driver => driver.status === 'active').map(driver => <option key={driver.id} value={driver.id}>{driver.full_name || driver.name}</option>)}</select></td></tr>)}</tbody></table></div>}</section>; }
function Payouts({ range, setRange, rows, paidIds, markPaid, exportCsv, loading }) { return <section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow mb-2">Driver Payouts</p><h2 className="text-2xl font-black">Payout overview</h2><p className="mt-1 text-sm text-slate-500">Gross fares, platform profit and driver pay for completed trips.</p></div><div className="flex flex-wrap gap-3"><select className="field w-auto min-w-[150px]" value={range} onChange={event => setRange(event.target.value)}>{Object.entries(rangeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button onClick={exportCsv} className="btn btn-outline text-sm"><Download size={16} /> Export to CSV</button></div></div>{loading ? <p className="mt-8 text-sm text-slate-500">Loading payouts...</p> : rows.length === 0 ? <p className="mt-8 rounded-xl border border-dashed border-slate-200 px-5 py-10 text-center text-sm text-slate-500">No active drivers found.</p> : <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase text-slate-400"><th className="pb-3">Driver Name</th><th className="pb-3">Phone</th><th className="pb-3">Car Plate</th><th className="pb-3">Trips Week</th><th className="pb-3">Gross Fare</th><th className="pb-3">Your Profit (20%)</th><th className="pb-3">To Pay Driver (80%)</th><th className="pb-3">All-time Earnings</th><th className="pb-3">Action</th></tr></thead><tbody>{rows.map(row => <tr key={row.driver.id} className="border-b border-slate-50"><td className="py-4 font-bold">{row.driver.full_name || row.driver.name}</td><td className="py-4">{row.driver.phone}</td><td className="py-4">{row.driver.car_plate || '-'}</td><td className="py-4">{row.trips}</td><td className="py-4">{money(row.gross)}</td><td className="py-4 text-brand">{money(row.platformFee)}</td><td className="py-4 font-bold">{money(row.driverPay)}</td><td className="py-4">{money(row.driver.total_earnings)}</td><td className="py-4"><button disabled={paidIds.has(row.driver.id) || row.trips === 0} onClick={() => markPaid(row)} className="btn btn-primary px-3 py-2 text-xs disabled:cursor-not-allowed disabled:opacity-50">{paidIds.has(row.driver.id) ? 'Paid' : row.trips === 0 ? 'No trips' : 'Mark as Paid'}</button></td></tr>)}</tbody></table></div>}</section>; }