'use client';

import { useState } from 'react';
import { ArrowUpRight, CheckCircle2, Clock3, LogOut, Truck, Wallet } from 'lucide-react';

export default function DriverDashboard() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [email, setEmail] = useState('');
  if (!loggedIn) return <main className="bg-mist"><div className="container flex min-h-[620px] items-center justify-center py-16"><form onSubmit={e => { e.preventDefault(); setLoggedIn(true); }} className="w-full max-w-md rounded-2xl bg-white p-8 shadow-soft"><div className="mb-8"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-xl bg-sky text-brand"><Truck /></div><p className="eyebrow mb-2">Driver portal</p><h1 className="text-3xl font-black tracking-[-.04em]">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Log in to see your jobs and earnings. Supabase Auth can be connected here when ready.</p></div><label className="mb-1.5 block text-xs font-bold text-slate-600">Email</label><input required type="email" className="field mb-4" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /><label className="mb-1.5 block text-xs font-bold text-slate-600">Password</label><input required type="password" className="field" placeholder="••••••••" /><button className="btn btn-primary mt-6 w-full">Log in <ArrowUpRight size={17} /></button></form></div></main>;
  return <main className="bg-mist"><div className="container py-12"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">Driver portal</p><h1 className="text-4xl font-black tracking-[-.045em]">Good morning.</h1><p className="mt-2 text-sm text-slate-500">Here is your workday at a glance.</p></div><button onClick={() => setLoggedIn(false)} className="flex items-center gap-2 self-start text-sm font-bold text-slate-500"><LogOut size={16} /> Log out</button></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-brand p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-200">This month</p><p className="mt-3 text-4xl font-black">R8,420</p><p className="mt-2 flex items-center gap-2 text-sm text-blue-100"><Wallet size={16} /> Your 85% payout</p></div><div className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Completed jobs</p><p className="mt-3 text-4xl font-black text-ink">18</p><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><CheckCircle2 size={16} className="text-green-600" /> 100% proof uploaded</p></div><div className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Rating</p><p className="mt-3 text-4xl font-black text-ink">4.9<span className="text-lg text-slate-400">/5</span></p><p className="mt-2 text-sm text-slate-500">From 32 client ratings</p></div></div><div className="mt-10 rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black">My jobs</h2><span className="rounded-full bg-lime-100 px-3 py-1 text-xs font-bold text-green-800">2 upcoming</span></div><div className="mt-5 divide-y divide-slate-100">{[['Today, 10:00','Strandfontein → Muizenberg','2-bedroom furniture move','R509 payout'],['Tomorrow, 08:30','Khayelitsha → CBD','Business delivery','R382 payout']].map(job => <div key={job[0]} className="flex flex-col justify-between gap-3 py-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-sm font-extrabold"><Clock3 size={16} className="text-brand" />{job[0]}</div><p className="mt-1 text-sm text-slate-600">{job[1]}</p><p className="mt-1 text-xs text-slate-400">{job[2]}</p></div><div className="flex items-center gap-4"><span className="text-sm font-black text-brand">{job[3]}</span><button className="btn btn-outline !px-3 !py-2 text-xs">View job</button></div></div>)}</div></div></div></main>;
}
