'use client';

import { useState } from 'react';
import { ImagePlus, ArrowUpRight, CheckCircle2 } from 'lucide-react';

const areas = ['Strandfontein','Mitchells Plain','Khayelitsha','Muizenberg','Cape Town CBD','Northern Suburbs','Constantia','Hout Bay','Other'];
export default function QuoteForm() {
  const [form, setForm] = useState({ name: '', phone: '', from: '', to: '', service: '', description: '' });
  const [error, setError] = useState('');
  const update = (key, value) => setForm({ ...form, [key]: value });
  const submit = (event) => { event.preventDefault(); if (!form.phone || !form.from || !form.service) { setError('Please add your phone, collection area and service.'); return; } setError(''); const message = `Hi JRMS, I would like a quote.%0A%0AName: ${form.name || 'Not provided'}%0APhone: ${form.phone}%0AFrom: ${form.from}%0ATo: ${form.to || 'Not provided'}%0AService: ${form.service}%0ADetails: ${form.description || 'Not provided'}`; window.open(`https://wa.me/27788868252?text=${message}`, '_blank'); };
  return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 block text-xs font-bold text-slate-600">Your name</label><input className="field" value={form.name} onChange={e => update('name', e.target.value)} placeholder="e.g. Aisha Daniels" /></div><div><label className="mb-1.5 block text-xs font-bold text-slate-600">WhatsApp number *</label><input required type="tel" className="field" value={form.phone} onChange={e => update('phone', e.target.value)} placeholder="078 886 8252" /></div><div><label className="mb-1.5 block text-xs font-bold text-slate-600">Collection area *</label><select required className="field" value={form.from} onChange={e => update('from', e.target.value)}><option value="">Select area</option>{areas.map(area => <option key={area}>{area}</option>)}</select></div><div><label className="mb-1.5 block text-xs font-bold text-slate-600">Delivery area</label><select className="field" value={form.to} onChange={e => update('to', e.target.value)}><option value="">Select area</option>{areas.map(area => <option key={area}>{area}</option>)}</select></div><div className="sm:col-span-2"><label className="mb-1.5 block text-xs font-bold text-slate-600">What do you need? *</label><select required className="field" value={form.service} onChange={e => update('service', e.target.value)}><option value="">Select a service</option><option>Furniture move</option><option>Junk removal & rubble</option><option>Business delivery</option></select></div><div className="sm:col-span-2"><label className="mb-1.5 block text-xs font-bold text-slate-600">A few details</label><textarea className="field min-h-24 resize-y" value={form.description} onChange={e => update('description', e.target.value)} placeholder="Items, floors, stairs, access or anything useful..." /></div><div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-slate-500"><ImagePlus size={17} className="text-brand" /> Photos can be sent in WhatsApp</div><button className="btn btn-primary" type="submit">Get quote on WhatsApp <ArrowUpRight size={17} /></button></div>{error && <p className="sm:col-span-2 flex items-center gap-2 text-sm font-semibold text-red-600"><CheckCircle2 size={16} />{error}</p>}</form>;
}
