'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, CheckCircle2 } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';

const initialForm = { fullName: '', phone: '', email: '', idNumber: '', carModel: '', carPlate: '', password: '', confirmPassword: '' };
const normalizePhone = value => { const digits = value.replace(/\D/g, ''); if (digits.startsWith('0')) return `+27${digits.slice(1)}`; return digits.startsWith('27') ? `+${digits}` : value.trim(); };

export default function DriverSignupPage() {
  const router = useRouter(); const [form, setForm] = useState(initialForm); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false);
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }));
  const submit = async event => { event.preventDefault(); setError(''); if (form.password !== form.confirmPassword) { setError('Passwords do not match.'); return; } if (!/^0[6-8]\d{8}$/.test(form.phone.replace(/\D/g, ''))) { setError('Enter a valid South African mobile number.'); return; } setLoading(true); const phone = normalizePhone(form.phone); const { data, error: authError } = await supabase.auth.signUp({ phone, password: form.password, options: { data: { full_name: form.fullName, email: form.email } } }); if (authError || !data.user) { setError(authError?.message || 'Unable to create your account.'); setLoading(false); return; } const { error: driverError } = await supabase.from('drivers').insert({ id: data.user.id, full_name: form.fullName, name: form.fullName, phone, email: form.email, id_number: form.idNumber, car_model: form.carModel, vehicle: form.carModel, area: 'Cape Town', car_plate: form.carPlate, status: 'pending', total_earnings: 0, total_trips: 0 }); if (driverError) { setError(driverError.message); setLoading(false); return; } await supabase.auth.signOut(); setSent(true); setLoading(false); };
  if (sent) return <main className="bg-mist"><div className="container flex min-h-[620px] items-center justify-center py-16"><div className="w-full max-w-md rounded-2xl bg-white p-8 text-center shadow-soft"><CheckCircle2 className="mx-auto text-green-600" size={48} /><h1 className="mt-5 text-3xl font-black">Application sent</h1><p className="mt-3 text-sm leading-6 text-slate-500">Application sent - waiting for admin approval</p><button onClick={() => router.push('/driver/login')} className="btn btn-primary mt-6 w-full">Go to driver login</button></div></div></main>;
  return <main className="bg-mist"><div className="container py-12"><form onSubmit={submit} className="mx-auto max-w-2xl rounded-2xl bg-white p-8 shadow-soft"><p className="eyebrow mb-2">Join JRMS</p><h1 className="text-3xl font-black tracking-[-.04em]">Driver application</h1><p className="mt-3 text-sm text-slate-500">Tell us about yourself and your vehicle.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{[['fullName','Full Name'],['phone','Phone Number'],['email','Email'],['idNumber','ID Number'],['carModel','Car Model'],['carPlate','Car Plate']].map(([name, label]) => <label key={name} className="text-xs font-bold text-slate-600">{label}<input required name={name} type={name === 'email' ? 'email' : 'text'} className="field mt-1.5" value={form[name]} onChange={update} placeholder={name === 'phone' ? '082 123 4567' : ''} /></label>)}<label className="text-xs font-bold text-slate-600">Password<input required minLength={8} name="password" type="password" className="field mt-1.5" value={form.password} onChange={update} /></label><label className="text-xs font-bold text-slate-600">Confirm Password<input required minLength={8} name="confirmPassword" type="password" className="field mt-1.5" value={form.confirmPassword} onChange={update} /></label></div>{error && <p className="mt-4 text-sm font-semibold text-red-600">{error}</p>}<button disabled={loading} className="btn btn-primary mt-7 w-full sm:w-auto">{loading ? 'Sending application...' : 'Submit application'} <ArrowUpRight size={17} /></button><p className="mt-6 text-sm text-slate-500">Already registered? <Link className="font-bold text-brand" href="/driver/login">Log in</Link></p></form></div></main>;
}